#!/bin/groovy
package ci

node {
    withEnv(['REPO=devops-case-study']) {
        switch (env.BRANCH) {
            case ~/release.*/:
                load('ci_helper/release.groovy')()
                break
            case ~/story.*/:
                load('ci_helper/development.groovy')()
                break
            default:
                println "No action performed, invalid branch selected"
                break
        }
    }
}
